Parallelize tests via CircleCI workflows

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,155 +1,190 @@
 version: 2
+
+references:
+  docker: &docker
+    - image: circleci/python:3.6.8-stretch
+  
+  checkout_code_and_setup_ci: &checkout_code_and_setup_ci
+    - checkout
+    
+    - run:
+      name: Set BASH_ENV
+      command: |
+        echo "set -e" >> $BASH_ENV;
+        echo "export DISPLAY=:99" >> $BASH_ENV;
+        echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
+        echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
+
+    - restore_cache:
+        keys:
+          - pip-cache-0
+
+    - restore_cache:
+        keys:
+          - data-cache-1
+
+    - run:
+        name: Get conda running
+        command: |
+          wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
+          chmod +x ~/miniconda.sh;
+          ~/miniconda.sh -b -p ~/miniconda;
+          echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
+
+    - run:
+        name: Install dependencies in conda base environment
+        command: |
+          conda update -n base -c defaults conda
+          pip install numpy scipy matplotlib nibabel
+          pip install -U scikit-learn
+          pip install --upgrade https://api.github.com/repos/mne-tools/mne-python/zipball/master
+          git clone https://github.com/mne-tools/mne-bids.git --depth 1
+          cd mne-bids
+          pip install -e .
+          cd ..
+
+    - run:
+        name: Spin up Xvfb
+        command: |
+          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
+
+    # https://github.com/ContinuumIO/anaconda-issues/issues/9190#issuecomment-386508136
+    # https://github.com/golemfactory/golem/issues/1019
+    - run:
+        name: Install PyQt5 dependencies
+        command: |
+          sudo apt-get install libxkbcommon-x11-0
+
+    - run:
+        name: Install 3D dependencies
+        command: |
+          pip install --user --upgrade --progress-bar off vtk
+          pip install --user --upgrade --progress-bar off mayavi
+          pip install --user --upgrade --progress-bar off PySurfer[save_movie]
+
+    - run:
+        name: Install datalad to conveniently pull testing datasets
+        command: |
+          conda install -c conda-forge git-annex
+          pip install --upgrade datalad
+          git config --global user.email "user@mne.com"
+          git config --global user.name "mne user"
+
+    # Save Python cache
+    - save_cache:
+        key: pip-cache-0
+        paths:
+          - ~/.cache/pip
+
+    # Look at what we have and fail early if there is some library conflict
+    - run:
+        name: Check installation
+        command: |
+          which python
+          git-annex version
+          datalad --version
+          mne_bids --version
+          mne --version
+          python -c "import mne; mne.sys_info()"
+
+    # Setup for report
+    - run:
+        name: Setup report
+        command: |
+          mkdir ~/reports
+
+  store_artifacts_and_save_cache: &store_artifacts_and_save_cache:
+    - store_artifacts:
+      path: /home/circleci/reports
+      destination: reports
+
+    - save_cache:
+        key: data-cache-1
+        paths:
+          - ~/mne_data/
+
 jobs:
-    run_tests:
-      docker:
-        - image: circleci/python:3.6.8-stretch
-      steps:
-        - checkout
+  ds000246:
+    <<: *docker
 
-        - run:
-            name: Set BASH_ENV
-            command: |
-              echo "set -e" >> $BASH_ENV;
-              echo "export DISPLAY=:99" >> $BASH_ENV;
-              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
-              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
+    steps:
+      - *checkout_code_and_setup_ci
+      - run:
+          name: test ds000246
+          command: |
+              export DS=ds000246
+              python tests/run_tests.py ${DS}
+              mkdir ~/reports/${DS}
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
+      - *store_artifacts_and_save_cache
+  
+  ds000248:
+    <<: *docker
 
-        - restore_cache:
-            keys:
-              - pip-cache-0
+    steps:
+      - *checkout_code_and_setup_ci
+      - run:
+          name: test ds000248
+          command: |
+              export DS=ds000248
+              python tests/run_tests.py ${DS}
+              mkdir ~/reports/${DS}
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
+      - *store_artifacts_and_save_cache
 
-        - restore_cache:
-            keys:
-              - data-cache-1
+  ds001810:
+    <<: *docker
 
-        - run:
-            name: Get conda running
-            command: |
-              wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
-              chmod +x ~/miniconda.sh;
-              ~/miniconda.sh -b -p ~/miniconda;
-              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;
+    steps:
+      - *checkout_code_and_setup_ci
+      - run:
+          name: test ds001810
+          command: |
+              export DS=ds001810
+              python tests/run_tests.py ${DS}
+              mkdir ~/reports/${DS}
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/*/report_*.html ~/reports/${DS}/
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
+      - *store_artifacts_and_save_cache
 
-        - run:
-            name: Install dependencies in conda base environment
-            command: |
-              conda update -n base -c defaults conda
-              pip install numpy scipy matplotlib nibabel
-              pip install -U scikit-learn
-              pip install --upgrade https://api.github.com/repos/mne-tools/mne-python/zipball/master
-              git clone https://github.com/mne-tools/mne-bids.git --depth 1
-              cd mne-bids
-              pip install -e .
-              cd ..
+  eeg_matchingpennies:
+    <<: *docker
 
-        - run:
-            name: Spin up Xvfb
-            command: |
-              /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
+    steps:
+      - *checkout_code_and_setup_ci
+      - run:
+          name: test eeg_matchingpennies
+          command: |
+              export DS=eeg_matchingpennies
+              python tests/run_tests.py ${DS}
+              mkdir ~/reports/${DS}
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
+              cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
+      - *store_artifacts_and_save_cache
 
-        # https://github.com/ContinuumIO/anaconda-issues/issues/9190#issuecomment-386508136
-        # https://github.com/golemfactory/golem/issues/1019
-        - run:
-            name: Install PyQt5 dependencies
-            command: |
-              sudo apt-get install libxkbcommon-x11-0
+  somato:
+    <<: *docker
 
-        - run:
-            name: Install 3D dependencies
-            command: |
-              pip install --user --upgrade --progress-bar off vtk
-              pip install --user --upgrade --progress-bar off mayavi
-              pip install --user --upgrade --progress-bar off PySurfer[save_movie]
-
-        - run:
-            name: Install datalad to conveniently pull testing datasets
-            command: |
-              conda install -c conda-forge git-annex
-              pip install --upgrade datalad
-              git config --global user.email "user@mne.com"
-              git config --global user.name "mne user"
-
-        # Save Python cache
-        - save_cache:
-            key: pip-cache-0
-            paths:
-              - ~/.cache/pip
-
-        # Look at what we have and fail early if there is some library conflict
-        - run:
-            name: Check installation
-            command: |
-               which python
-               git-annex version
-               datalad --version
-               mne_bids --version
-               mne --version
-               python -c "import mne; mne.sys_info()"
-
-        # Setup for report
-        - run:
-            name: Setup report
-            command: |
-               mkdir ~/reports
-
-        # Run tests
-        - run:
-            name: test ds000246
-            command: |
-               export DS=ds000246
-               python tests/run_tests.py ${DS}
-               mkdir ~/reports/${DS}
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
-
-        - run:
-            name: test ds000248
-            command: |
-               export DS=ds000248
-               python tests/run_tests.py ${DS}
-               mkdir ~/reports/${DS}
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
-
-        - run:
-            name: test ds001810
-            command: |
-               export DS=ds001810
-               python tests/run_tests.py ${DS}
-               mkdir ~/reports/${DS}
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/*/report_*.html ~/reports/${DS}/
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
-
-        - run:
-            name: test eeg_matchingpennies
-            command: |
-               export DS=eeg_matchingpennies
-               python tests/run_tests.py ${DS}
-               mkdir ~/reports/${DS}
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
-               cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
-
-        - run:
-            name: test somato
-            command: |
-               export DS=somato
-               python tests/run_tests.py ${DS}
-               # mkdir ~/reports/${DS}
-               # cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
-               # cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
-
-        - store_artifacts:
-            path: /home/circleci/reports
-            destination: reports
-
-        - save_cache:
-            key: data-cache-1
-            paths:
-              - ~/mne_data/
+    steps:
+      - *checkout_code_and_setup_ci
+      - run:
+          name: test somato
+          command: |
+              export DS=somato
+              python tests/run_tests.py ${DS}
+              # mkdir ~/reports/${DS}
+              # cp ~/mne_data/${DS}/derivatives/mne-study-template/*/*/report_*.html ~/reports/${DS}/
+              # cp ~/mne_data/${DS}/derivatives/mne-study-template/report_average_*.html ~/reports/${DS}/
+      - *store_artifacts_and_save_cache
 
 workflows:
   version: 2
-
-  default:
+  build_and_test:
     jobs:
-      - run_tests
+      - ds000246
+      - ds000248
+      - ds001810
+      - eeg_matchingpennies
+      - somato
