ENH: Bump uv deps

diff --git a/.github/workflows/autofix.yml b/.github/workflows/autofix.yml
--- a/.github/workflows/autofix.yml
+++ b/.github/workflows/autofix.yml
@@ -3,18 +3,47 @@ name: autofix.ci
 on:
   pull_request:
     types: [opened, synchronize, reopened]
+  schedule:
+    - cron: '0 0 1 * *'  # At 00:00 on day-of-month 1
+  workflow_dispatch:
 
 permissions:
-  contents: read
+  contents: write
 
 jobs:
   autofix:
+    env:
+      # Will use MNE_BOT_TOKEN when running from workflow_dispatch or schedule
+      GITHUB_TOKEN: ${{ secrets.MNE_BOT_TOKEN || secrets.GITHUB_TOKEN }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          token: ${{ env.GITHUB_TOKEN}}
       - uses: astral-sh/setup-uv@v7
-      - run: uv sync --locked
+      #- run: uv sync --locked
+      #  if: github.event_name == 'pull_request'
+      - run: uv sync --upgrade
+        #if: github.event_name != 'pull_request'
       - run: uv lock
       - run: uv run lefthook run pre-commit --all-files
-      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
-        if: failure() || success()
+      #- uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
+      #  if: github.event_name == 'pull_request' && (failure() || success())
+      - name: Create PR
+        # if: github.event_name != 'pull_request' && (failure() || success())
+        run: |
+          git diff && git status --porcelain
+          if [[ ! $(git status --porcelain) ]]; then
+            echo "No changes to commit"
+            exit 0
+          fi
+          set -xeo pipefail
+          git config --global user.email "50266005+mne-bot@users.noreply.github.com"
+          git config --global user.name "mne[bot]"
+          BRANCH=uv/$(date '+%Y%m%d')
+          git checkout -b $BRANCH
+          git commit -am "mne[bot]: Update uv.lock"
+          git push origin $BRANCH
+          PR_NUM=$(gh pr create --base main --head $BRANCH --title "Upgrade uv deps" --body "Created by credit [GitHub action](https://github.com/mne-tools/mne-bids-pipeline/actions/runs/${{ github.run_id }}).")
+          echo "Opened https://github.com/mne-tools/mne-python/pull/${PR_NUM}" >> $GITHUB_STEP_SUMMARY
